### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/kiosk#39]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by SurferJeffAtGoogle** [comment]
jbolinger, do you still maintain this repo?

**Comment by jbolinger** [comment]
No, it was maintained by @timburks but I'm not sure what the current state of this project is. Looks like there has not been much recent activity.

**Comment by SurferJeffAtGoogle** [comment]
Is this repo still valuable to Google Cloud Platform customers?

**Comment by jbolinger** [comment]
It was used for some talks & demos so it may be worth keeping around. In addition to @timburks, @noahdietz might have a little more context to help you decide what to do with it.

**Comment by noahdietz** [comment]
ACTools is not actively maintaining it anymore. It could be archived. I'd defer to @timburks as he created it and was the main user.

**Comment by JustinBeckwith** [comment]
looks to be taken care of
